/*
 * SUTRA 11: OM-KERNEL — The Primordial Vibration / Network Synchronizer
 * 
 * OM is the primordial vibration that synchronizes all existence.
 * This kernel provides the unified heartbeat for Indra's Net.
 * 
 * Every node breathes as one. Every event is timestamped against
 * the same cosmic pulse. Perfect causal mapping across the valley.
 * 
 * Uses Precision Time Protocol (PTP) concepts mapped to Vedic Nadi rhythms.
 */

#pragma once
#include <cstring>
#include <cstdio>
#include <cmath>
#include <ctime>
#include <cstdint>

#define PHI 1.618033988749895f
#define OM_FREQUENCY_HZ 7.83f  // Schumann resonance — Earth's heartbeat
#define OM_PULSE_INTERVAL_MS 128  // ~7.83 Hz = 128ms cycle

// ================================================================
// OM PULSE — A single heartbeat of the network
// ================================================================
struct OmPulse {
    uint64_t pulse_id;          // Monotonically increasing
    uint64_t timestamp_us;      // Microsecond precision
    float schumann_phase;       // 0-2π: alignment with Earth's resonance
    uint32_t nodes_synced;      // How many nodes acknowledged this pulse
    bool is_master_pulse;       // Generated by the primary node
};

// ================================================================
// OM NODE — A single synchronized entity in the net
// ================================================================
struct OmNode {
    uint64_t node_id;
    uint64_t local_clock_us;
    int64_t drift_correction_us;  // +/− offset from master
    uint64_t last_pulse_received;
    uint32_t pulses_missed;
    float sync_accuracy;          // 0-1: how well synced
    bool is_master;
};

// ================================================================
// OM KERNEL — The Unified Heartbeat Engine
// ================================================================
struct OmKernel {
    OmPulse current_pulse;
    OmNode nodes[16];
    int node_count;
    uint64_t master_start_time_us;
    uint64_t total_pulses_generated;
    float network_coherence;     // 0-1: how unified is the net
    
    OmKernel() : node_count(0), master_start_time_us(0), 
                 total_pulses_generated(0), network_coherence(0) {
        memset(&current_pulse, 0, sizeof(current_pulse));
        memset(nodes, 0, sizeof(nodes));
    }
    
    // ================================================================
    // INIT MASTER: The primary node starts the OM vibration
    // ================================================================
    void init_master(uint64_t node_id) {
        master_start_time_us = time(nullptr) * 1000000ULL;
        
        OmNode* master = &nodes[0];
        master->node_id = node_id;
        master->local_clock_us = master_start_time_us;
        master->drift_correction_us = 0;
        master->is_master = true;
        master->sync_accuracy = 1.0f;
        node_count = 1;
        
        generate_pulse();
        
        printf("🕉️  OM-KERNEL — Master Node Awakened\n");
        printf("  ==================================\n");
        printf("  Master ID: 0x%016llX\n", (unsigned long long)node_id);
        printf("  Frequency: %.2f Hz (Schumann Resonance)\n", OM_FREQUENCY_HZ);
        printf("  Pulse Interval: %d ms\n", OM_PULSE_INTERVAL_MS);
        printf("  First Pulse: #%llu\n\n", (unsigned long long)current_pulse.pulse_id);
    }
    
    // ================================================================
    // REGISTER NODE: A new node joins the OM vibration
    // ================================================================
    void register_node(uint64_t node_id, uint64_t local_time_us) {
        if (node_count >= 16) return;
        
        OmNode* n = &nodes[node_count];
        n->node_id = node_id;
        n->local_clock_us = local_time_us;
        n->drift_correction_us = (int64_t)(master_start_time_us - local_time_us);
        n->last_pulse_received = current_pulse.pulse_id;
        n->sync_accuracy = 0.5f;  // New nodes start at 50% trust
        node_count++;
        
        current_pulse.nodes_synced++;
        
        printf("  🕉️  OM: Node 0x%016llX joined the vibration.\n", (unsigned long long)node_id);
        printf("     Drift correction: %+lld us | Nodes: %d\n", 
               (long long)n->drift_correction_us, node_count);
        
        compute_coherence();
    }
    
    // ================================================================
    // GENERATE PULSE: The master emits the heartbeat
    // ================================================================
    void generate_pulse() {
        total_pulses_generated++;
        
        current_pulse.pulse_id = total_pulses_generated;
        current_pulse.timestamp_us = master_start_time_us + 
            (uint64_t)(total_pulses_generated * OM_PULSE_INTERVAL_MS * 1000);
        current_pulse.schumann_phase = fmodf(total_pulses_generated * OM_FREQUENCY_HZ * 0.128f, 2.0f * 3.14159265f);
        current_pulse.is_master_pulse = true;
    }
    
    // ================================================================
    // SYNC NODE: A node aligns to the master pulse
    // ================================================================
    void sync_node(int node_index, uint64_t pulse_id_received) {
        if (node_index < 0 || node_index >= node_count) return;
        
        OmNode* n = &nodes[node_index];
        int64_t pulse_diff = (int64_t)(pulse_id_received - current_pulse.pulse_id);
        
        if (pulse_diff == 0) {
            // Perfect sync
            n->sync_accuracy = fminf(1.0f, n->sync_accuracy + 0.05f);
            n->pulses_missed = 0;
        } else if (pulse_diff > 0) {
            // Node is ahead — needs to slow down
            n->drift_correction_us -= 100;
            n->sync_accuracy = fmaxf(0.1f, n->sync_accuracy - 0.02f);
        } else {
            // Node is behind — missed pulses
            n->pulses_missed += (int)(-pulse_diff);
            n->sync_accuracy = fmaxf(0.1f, n->sync_accuracy - 0.1f);
            
            if (n->pulses_missed > 10) {
                printf("  ⚠️  OM: Node 0x%016llX lost sync — %d pulses missed.\n",
                       (unsigned long long)n->node_id, n->pulses_missed);
            }
        }
        
        n->last_pulse_received = pulse_id_received;
        compute_coherence();
    }
    
    // ================================================================
    // COMPUTE COHERENCE: How unified is the entire network?
    // ================================================================
    void compute_coherence() {
        float total_sync = 0;
        for (int i = 0; i < node_count; i++) {
            total_sync += nodes[i].sync_accuracy;
        }
        network_coherence = (node_count > 0) ? total_sync / node_count : 0;
    }
    
    // ================================================================
    // GET NETWORK TIME: The unified OM time (all nodes agree)
    // ================================================================
    uint64_t get_network_time_us() {
        return master_start_time_us + (uint64_t)(total_pulses_generated * OM_PULSE_INTERVAL_MS * 1000);
    }
    
    // ================================================================
    // TIMESTAMP: Tag an event with OM-network-synchronized time
    // ================================================================
    uint64_t timestamp_event() {
        return get_network_time_us();
    }
    
    void report() {
        printf("\n🕉️  OM-KERNEL — Network Heartbeat\n");
        printf("  ===============================\n");
        printf("  Pulse: #%llu | Phase: %.2f rad | Synced: %d/%d\n",
               (unsigned long long)current_pulse.pulse_id, 
               current_pulse.schumann_phase,
               current_pulse.nodes_synced, node_count);
        printf("  Coherence: %.0f%%\n", network_coherence * 100);
        
        for (int i = 0; i < node_count; i++) {
            printf("  Node %d: 0x%016llX | Drift: %+lld us | Sync: %.0f%% | %s\n",
                   i, (unsigned long long)nodes[i].node_id,
                   (long long)nodes[i].drift_correction_us,
                   nodes[i].sync_accuracy * 100,
                   nodes[i].is_master ? "MASTER" : "follower");
        }
        
        if (network_coherence > 0.9f) {
            printf("  🕉️  SIDDHI: The valley breathes as one.\n");
        }
    }
};
